// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bpgjjnibjdfzkvmpyizy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJwZ2pqbmliamRmemt2bXB5aXp5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MTAzMzIsImV4cCI6MjA2NTQ4NjMzMn0.rWFkiae0PmaO2HWoYFe7EZmomdOiOqRk-Muw892Nh4M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);